//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 2/23/2010 6:58:02 AM
namespace OPGOV
{
    
    /// <summary>
    /// There are no comments for OpenGOVideoEntities in the schema.
    /// </summary>
    public partial class OpenGOVideoEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new OpenGOVideoEntities object using the connection string found in the 'OpenGOVideoEntities' section of the application configuration file.
        /// </summary>
        public OpenGOVideoEntities() : 
                base("name=OpenGOVideoEntities", "OpenGOVideoEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new OpenGOVideoEntities object.
        /// </summary>
        public OpenGOVideoEntities(string connectionString) : 
                base(connectionString, "OpenGOVideoEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new OpenGOVideoEntities object.
        /// </summary>
        public OpenGOVideoEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "OpenGOVideoEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Agenda in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Agenda> Agenda
        {
            get
            {
                if ((this._Agenda == null))
                {
                    this._Agenda = base.CreateQuery<Agenda>("[Agenda]");
                }
                return this._Agenda;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Agenda> _Agenda;
        /// <summary>
        /// There are no comments for AgendaDetails in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<AgendaDetails> AgendaDetails
        {
            get
            {
                if ((this._AgendaDetails == null))
                {
                    this._AgendaDetails = base.CreateQuery<AgendaDetails>("[AgendaDetails]");
                }
                return this._AgendaDetails;
            }
        }
        private global::System.Data.Objects.ObjectQuery<AgendaDetails> _AgendaDetails;
        /// <summary>
        /// There are no comments for Client in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Client> Client
        {
            get
            {
                if ((this._Client == null))
                {
                    this._Client = base.CreateQuery<Client>("[Client]");
                }
                return this._Client;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Client> _Client;
        /// <summary>
        /// There are no comments for vFullAgenda in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<vFullAgenda> vFullAgenda
        {
            get
            {
                if ((this._vFullAgenda == null))
                {
                    this._vFullAgenda = base.CreateQuery<vFullAgenda>("[vFullAgenda]");
                }
                return this._vFullAgenda;
            }
        }
        private global::System.Data.Objects.ObjectQuery<vFullAgenda> _vFullAgenda;
        /// <summary>
        /// There are no comments for Agenda in the schema.
        /// </summary>
        public void AddToAgenda(Agenda agenda)
        {
            base.AddObject("Agenda", agenda);
        }
        /// <summary>
        /// There are no comments for AgendaDetails in the schema.
        /// </summary>
        public void AddToAgendaDetails(AgendaDetails agendaDetails)
        {
            base.AddObject("AgendaDetails", agendaDetails);
        }
        /// <summary>
        /// There are no comments for Client in the schema.
        /// </summary>
        public void AddToClient(Client client)
        {
            base.AddObject("Client", client);
        }
        /// <summary>
        /// There are no comments for vFullAgenda in the schema.
        /// </summary>
        public void AddTovFullAgenda(vFullAgenda vFullAgenda)
        {
            base.AddObject("vFullAgenda", vFullAgenda);
        }
    }
    /// <summary>
    /// There are no comments for Data.Model.Agenda in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ClientID
    /// AgendaID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Data.Model", Name="Agenda")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Agenda : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Agenda object.
        /// </summary>
        /// <param name="clientID">Initial value of ClientID.</param>
        /// <param name="agendaID">Initial value of AgendaID.</param>
        public static Agenda CreateAgenda(int clientID, int agendaID)
        {
            Agenda agenda = new Agenda();
            agenda.ClientID = clientID;
            agenda.AgendaID = agendaID;
            return agenda;
        }
        /// <summary>
        /// There are no comments for Property ClientID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientID
        {
            get
            {
                return this._ClientID;
            }
            set
            {
                this.OnClientIDChanging(value);
                this.ReportPropertyChanging("ClientID");
                this._ClientID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ClientID");
                this.OnClientIDChanged();
            }
        }
        private int _ClientID;
        partial void OnClientIDChanging(int value);
        partial void OnClientIDChanged();
        /// <summary>
        /// There are no comments for Property AgendaID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int AgendaID
        {
            get
            {
                return this._AgendaID;
            }
            set
            {
                this.OnAgendaIDChanging(value);
                this.ReportPropertyChanging("AgendaID");
                this._AgendaID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AgendaID");
                this.OnAgendaIDChanged();
            }
        }
        private int _AgendaID;
        partial void OnAgendaIDChanging(int value);
        partial void OnAgendaIDChanged();
        /// <summary>
        /// There are no comments for Property MeetingDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> MeetingDate
        {
            get
            {
                return this._MeetingDate;
            }
            set
            {
                this.OnMeetingDateChanging(value);
                this.ReportPropertyChanging("MeetingDate");
                this._MeetingDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MeetingDate");
                this.OnMeetingDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _MeetingDate;
        partial void OnMeetingDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnMeetingDateChanged();
        /// <summary>
        /// There are no comments for Property MeetingTime in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> MeetingTime
        {
            get
            {
                return this._MeetingTime;
            }
            set
            {
                this.OnMeetingTimeChanging(value);
                this.ReportPropertyChanging("MeetingTime");
                this._MeetingTime = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MeetingTime");
                this.OnMeetingTimeChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _MeetingTime;
        partial void OnMeetingTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnMeetingTimeChanged();
        /// <summary>
        /// There are no comments for Property DateSent in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> DateSent
        {
            get
            {
                return this._DateSent;
            }
            set
            {
                this.OnDateSentChanging(value);
                this.ReportPropertyChanging("DateSent");
                this._DateSent = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DateSent");
                this.OnDateSentChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _DateSent;
        partial void OnDateSentChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnDateSentChanged();
        /// <summary>
        /// There are no comments for Property DateReceived in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> DateReceived
        {
            get
            {
                return this._DateReceived;
            }
            set
            {
                this.OnDateReceivedChanging(value);
                this.ReportPropertyChanging("DateReceived");
                this._DateReceived = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DateReceived");
                this.OnDateReceivedChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _DateReceived;
        partial void OnDateReceivedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnDateReceivedChanged();
        /// <summary>
        /// There are no comments for Property DateCreated in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> DateCreated
        {
            get
            {
                return this._DateCreated;
            }
            set
            {
                this.OnDateCreatedChanging(value);
                this.ReportPropertyChanging("DateCreated");
                this._DateCreated = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DateCreated");
                this.OnDateCreatedChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _DateCreated;
        partial void OnDateCreatedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnDateCreatedChanged();
        /// <summary>
        /// There are no comments for Property DateModified in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> DateModified
        {
            get
            {
                return this._DateModified;
            }
            set
            {
                this.OnDateModifiedChanging(value);
                this.ReportPropertyChanging("DateModified");
                this._DateModified = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DateModified");
                this.OnDateModifiedChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _DateModified;
        partial void OnDateModifiedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnDateModifiedChanged();
        /// <summary>
        /// There are no comments for Property IsActive in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                this.OnIsActiveChanging(value);
                this.ReportPropertyChanging("IsActive");
                this._IsActive = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsActive");
                this.OnIsActiveChanged();
            }
        }
        private global::System.Nullable<bool> _IsActive;
        partial void OnIsActiveChanging(global::System.Nullable<bool> value);
        partial void OnIsActiveChanged();
    }
    /// <summary>
    /// There are no comments for Data.Model.AgendaDetails in the schema.
    /// </summary>
    /// <KeyProperties>
    /// AgendaID
    /// ItemID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Data.Model", Name="AgendaDetails")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class AgendaDetails : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new AgendaDetails object.
        /// </summary>
        /// <param name="agendaID">Initial value of AgendaID.</param>
        /// <param name="itemID">Initial value of ItemID.</param>
        /// <param name="parentItemID">Initial value of ParentItemID.</param>
        public static AgendaDetails CreateAgendaDetails(int agendaID, int itemID, int parentItemID)
        {
            AgendaDetails agendaDetails = new AgendaDetails();
            agendaDetails.AgendaID = agendaID;
            agendaDetails.ItemID = itemID;
            agendaDetails.ParentItemID = parentItemID;
            return agendaDetails;
        }
        /// <summary>
        /// There are no comments for Property AgendaID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int AgendaID
        {
            get
            {
                return this._AgendaID;
            }
            set
            {
                this.OnAgendaIDChanging(value);
                this.ReportPropertyChanging("AgendaID");
                this._AgendaID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AgendaID");
                this.OnAgendaIDChanged();
            }
        }
        private int _AgendaID;
        partial void OnAgendaIDChanging(int value);
        partial void OnAgendaIDChanged();
        /// <summary>
        /// There are no comments for Property ItemID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemID
        {
            get
            {
                return this._ItemID;
            }
            set
            {
                this.OnItemIDChanging(value);
                this.ReportPropertyChanging("ItemID");
                this._ItemID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ItemID");
                this.OnItemIDChanged();
            }
        }
        private int _ItemID;
        partial void OnItemIDChanging(int value);
        partial void OnItemIDChanged();
        /// <summary>
        /// There are no comments for Property ParentItemID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentItemID
        {
            get
            {
                return this._ParentItemID;
            }
            set
            {
                this.OnParentItemIDChanging(value);
                this.ReportPropertyChanging("ParentItemID");
                this._ParentItemID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ParentItemID");
                this.OnParentItemIDChanged();
            }
        }
        private int _ParentItemID;
        partial void OnParentItemIDChanging(int value);
        partial void OnParentItemIDChanged();
        /// <summary>
        /// There are no comments for Property ItemFrame in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> ItemFrame
        {
            get
            {
                return this._ItemFrame;
            }
            set
            {
                this.OnItemFrameChanging(value);
                this.ReportPropertyChanging("ItemFrame");
                this._ItemFrame = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ItemFrame");
                this.OnItemFrameChanged();
            }
        }
        private global::System.Nullable<int> _ItemFrame;
        partial void OnItemFrameChanging(global::System.Nullable<int> value);
        partial void OnItemFrameChanged();
        /// <summary>
        /// There are no comments for Property ItemPosition in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<float> ItemPosition
        {
            get
            {
                return this._ItemPosition;
            }
            set
            {
                this.OnItemPositionChanging(value);
                this.ReportPropertyChanging("ItemPosition");
                this._ItemPosition = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ItemPosition");
                this.OnItemPositionChanged();
            }
        }
        private global::System.Nullable<float> _ItemPosition;
        partial void OnItemPositionChanging(global::System.Nullable<float> value);
        partial void OnItemPositionChanged();
        /// <summary>
        /// There are no comments for Property Notes in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes
        {
            get
            {
                return this._Notes;
            }
            set
            {
                this.OnNotesChanging(value);
                this.ReportPropertyChanging("Notes");
                this._Notes = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Notes");
                this.OnNotesChanged();
            }
        }
        private string _Notes;
        partial void OnNotesChanging(string value);
        partial void OnNotesChanged();
    }
    /// <summary>
    /// There are no comments for Data.Model.Client in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ClientID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Data.Model", Name="Client")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Client : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Client object.
        /// </summary>
        /// <param name="clientID">Initial value of ClientID.</param>
        /// <param name="state">Initial value of State.</param>
        public static Client CreateClient(int clientID, string state)
        {
            Client client = new Client();
            client.ClientID = clientID;
            client.State = state;
            return client;
        }
        /// <summary>
        /// There are no comments for Property ClientID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientID
        {
            get
            {
                return this._ClientID;
            }
            set
            {
                this.OnClientIDChanging(value);
                this.ReportPropertyChanging("ClientID");
                this._ClientID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ClientID");
                this.OnClientIDChanged();
            }
        }
        private int _ClientID;
        partial void OnClientIDChanging(int value);
        partial void OnClientIDChanged();
        /// <summary>
        /// There are no comments for Property State in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this._State;
            }
            set
            {
                this.OnStateChanging(value);
                this.ReportPropertyChanging("State");
                this._State = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("State");
                this.OnStateChanged();
            }
        }
        private string _State;
        partial void OnStateChanging(string value);
        partial void OnStateChanged();
        /// <summary>
        /// There are no comments for Property City in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this._City;
            }
            set
            {
                this.OnCityChanging(value);
                this.ReportPropertyChanging("City");
                this._City = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("City");
                this.OnCityChanged();
            }
        }
        private string _City;
        partial void OnCityChanging(string value);
        partial void OnCityChanged();
        /// <summary>
        /// There are no comments for Property Board in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Board
        {
            get
            {
                return this._Board;
            }
            set
            {
                this.OnBoardChanging(value);
                this.ReportPropertyChanging("Board");
                this._Board = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Board");
                this.OnBoardChanged();
            }
        }
        private string _Board;
        partial void OnBoardChanging(string value);
        partial void OnBoardChanged();
        /// <summary>
        /// There are no comments for Property ClientName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientName
        {
            get
            {
                return this._ClientName;
            }
            set
            {
                this.OnClientNameChanging(value);
                this.ReportPropertyChanging("ClientName");
                this._ClientName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ClientName");
                this.OnClientNameChanged();
            }
        }
        private string _ClientName;
        partial void OnClientNameChanging(string value);
        partial void OnClientNameChanged();
        /// <summary>
        /// There are no comments for Property ContactName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactName
        {
            get
            {
                return this._ContactName;
            }
            set
            {
                this.OnContactNameChanging(value);
                this.ReportPropertyChanging("ContactName");
                this._ContactName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ContactName");
                this.OnContactNameChanged();
            }
        }
        private string _ContactName;
        partial void OnContactNameChanging(string value);
        partial void OnContactNameChanged();
        /// <summary>
        /// There are no comments for Property ContactTitle in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactTitle
        {
            get
            {
                return this._ContactTitle;
            }
            set
            {
                this.OnContactTitleChanging(value);
                this.ReportPropertyChanging("ContactTitle");
                this._ContactTitle = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ContactTitle");
                this.OnContactTitleChanged();
            }
        }
        private string _ContactTitle;
        partial void OnContactTitleChanging(string value);
        partial void OnContactTitleChanged();
        /// <summary>
        /// There are no comments for Property ContactEmailAddress in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactEmailAddress
        {
            get
            {
                return this._ContactEmailAddress;
            }
            set
            {
                this.OnContactEmailAddressChanging(value);
                this.ReportPropertyChanging("ContactEmailAddress");
                this._ContactEmailAddress = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ContactEmailAddress");
                this.OnContactEmailAddressChanged();
            }
        }
        private string _ContactEmailAddress;
        partial void OnContactEmailAddressChanging(string value);
        partial void OnContactEmailAddressChanged();
        /// <summary>
        /// There are no comments for Property ContactPhone01 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactPhone01
        {
            get
            {
                return this._ContactPhone01;
            }
            set
            {
                this.OnContactPhone01Changing(value);
                this.ReportPropertyChanging("ContactPhone01");
                this._ContactPhone01 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ContactPhone01");
                this.OnContactPhone01Changed();
            }
        }
        private string _ContactPhone01;
        partial void OnContactPhone01Changing(string value);
        partial void OnContactPhone01Changed();
        /// <summary>
        /// There are no comments for Property ContactPhone01X in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactPhone01X
        {
            get
            {
                return this._ContactPhone01X;
            }
            set
            {
                this.OnContactPhone01XChanging(value);
                this.ReportPropertyChanging("ContactPhone01X");
                this._ContactPhone01X = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ContactPhone01X");
                this.OnContactPhone01XChanged();
            }
        }
        private string _ContactPhone01X;
        partial void OnContactPhone01XChanging(string value);
        partial void OnContactPhone01XChanged();
        /// <summary>
        /// There are no comments for Property ContactPhone02 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactPhone02
        {
            get
            {
                return this._ContactPhone02;
            }
            set
            {
                this.OnContactPhone02Changing(value);
                this.ReportPropertyChanging("ContactPhone02");
                this._ContactPhone02 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ContactPhone02");
                this.OnContactPhone02Changed();
            }
        }
        private string _ContactPhone02;
        partial void OnContactPhone02Changing(string value);
        partial void OnContactPhone02Changed();
        /// <summary>
        /// There are no comments for Property ContactPhone02x in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactPhone02x
        {
            get
            {
                return this._ContactPhone02x;
            }
            set
            {
                this.OnContactPhone02xChanging(value);
                this.ReportPropertyChanging("ContactPhone02x");
                this._ContactPhone02x = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ContactPhone02x");
                this.OnContactPhone02xChanged();
            }
        }
        private string _ContactPhone02x;
        partial void OnContactPhone02xChanging(string value);
        partial void OnContactPhone02xChanged();
        /// <summary>
        /// There are no comments for Property ClientWebSite in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientWebSite
        {
            get
            {
                return this._ClientWebSite;
            }
            set
            {
                this.OnClientWebSiteChanging(value);
                this.ReportPropertyChanging("ClientWebSite");
                this._ClientWebSite = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ClientWebSite");
                this.OnClientWebSiteChanged();
            }
        }
        private string _ClientWebSite;
        partial void OnClientWebSiteChanging(string value);
        partial void OnClientWebSiteChanged();
        /// <summary>
        /// There are no comments for Property PublishingPointAddress in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PublishingPointAddress
        {
            get
            {
                return this._PublishingPointAddress;
            }
            set
            {
                this.OnPublishingPointAddressChanging(value);
                this.ReportPropertyChanging("PublishingPointAddress");
                this._PublishingPointAddress = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PublishingPointAddress");
                this.OnPublishingPointAddressChanged();
            }
        }
        private string _PublishingPointAddress;
        partial void OnPublishingPointAddressChanging(string value);
        partial void OnPublishingPointAddressChanged();
        /// <summary>
        /// There are no comments for Property StreamUserName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string StreamUserName
        {
            get
            {
                return this._StreamUserName;
            }
            set
            {
                this.OnStreamUserNameChanging(value);
                this.ReportPropertyChanging("StreamUserName");
                this._StreamUserName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("StreamUserName");
                this.OnStreamUserNameChanged();
            }
        }
        private string _StreamUserName;
        partial void OnStreamUserNameChanging(string value);
        partial void OnStreamUserNameChanged();
        /// <summary>
        /// There are no comments for Property StreamPassword in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string StreamPassword
        {
            get
            {
                return this._StreamPassword;
            }
            set
            {
                this.OnStreamPasswordChanging(value);
                this.ReportPropertyChanging("StreamPassword");
                this._StreamPassword = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("StreamPassword");
                this.OnStreamPasswordChanged();
            }
        }
        private string _StreamPassword;
        partial void OnStreamPasswordChanging(string value);
        partial void OnStreamPasswordChanged();
        /// <summary>
        /// There are no comments for Property IsActive in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                this.OnIsActiveChanging(value);
                this.ReportPropertyChanging("IsActive");
                this._IsActive = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsActive");
                this.OnIsActiveChanged();
            }
        }
        private global::System.Nullable<bool> _IsActive;
        partial void OnIsActiveChanging(global::System.Nullable<bool> value);
        partial void OnIsActiveChanged();
        /// <summary>
        /// There are no comments for Property DateAdded in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> DateAdded
        {
            get
            {
                return this._DateAdded;
            }
            set
            {
                this.OnDateAddedChanging(value);
                this.ReportPropertyChanging("DateAdded");
                this._DateAdded = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DateAdded");
                this.OnDateAddedChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _DateAdded;
        partial void OnDateAddedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnDateAddedChanged();
        /// <summary>
        /// There are no comments for Property ExpirationDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> ExpirationDate
        {
            get
            {
                return this._ExpirationDate;
            }
            set
            {
                this.OnExpirationDateChanging(value);
                this.ReportPropertyChanging("ExpirationDate");
                this._ExpirationDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ExpirationDate");
                this.OnExpirationDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _ExpirationDate;
        partial void OnExpirationDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnExpirationDateChanged();
    }
    /// <summary>
    /// There are no comments for Data.Model.vFullAgenda in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ClientID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Data.Model", Name="vFullAgenda")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class vFullAgenda : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new vFullAgenda object.
        /// </summary>
        /// <param name="clientID">Initial value of ClientID.</param>
        public static vFullAgenda CreatevFullAgenda(int clientID)
        {
            vFullAgenda vFullAgenda = new vFullAgenda();
            vFullAgenda.ClientID = clientID;
            return vFullAgenda;
        }
        /// <summary>
        /// There are no comments for Property ClientID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientID
        {
            get
            {
                return this._ClientID;
            }
            set
            {
                this.OnClientIDChanging(value);
                this.ReportPropertyChanging("ClientID");
                this._ClientID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ClientID");
                this.OnClientIDChanged();
            }
        }
        private int _ClientID;
        partial void OnClientIDChanging(int value);
        partial void OnClientIDChanged();
        /// <summary>
        /// There are no comments for Property AgendaID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> AgendaID
        {
            get
            {
                return this._AgendaID;
            }
            set
            {
                this.OnAgendaIDChanging(value);
                this.ReportPropertyChanging("AgendaID");
                this._AgendaID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AgendaID");
                this.OnAgendaIDChanged();
            }
        }
        private global::System.Nullable<int> _AgendaID;
        partial void OnAgendaIDChanging(global::System.Nullable<int> value);
        partial void OnAgendaIDChanged();
        /// <summary>
        /// There are no comments for Property MeetingDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> MeetingDate
        {
            get
            {
                return this._MeetingDate;
            }
            set
            {
                this.OnMeetingDateChanging(value);
                this.ReportPropertyChanging("MeetingDate");
                this._MeetingDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MeetingDate");
                this.OnMeetingDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _MeetingDate;
        partial void OnMeetingDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnMeetingDateChanged();
        /// <summary>
        /// There are no comments for Property MeetingTime in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> MeetingTime
        {
            get
            {
                return this._MeetingTime;
            }
            set
            {
                this.OnMeetingTimeChanging(value);
                this.ReportPropertyChanging("MeetingTime");
                this._MeetingTime = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MeetingTime");
                this.OnMeetingTimeChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _MeetingTime;
        partial void OnMeetingTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnMeetingTimeChanged();
        /// <summary>
        /// There are no comments for Property ItemID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> ItemID
        {
            get
            {
                return this._ItemID;
            }
            set
            {
                this.OnItemIDChanging(value);
                this.ReportPropertyChanging("ItemID");
                this._ItemID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ItemID");
                this.OnItemIDChanged();
            }
        }
        private global::System.Nullable<int> _ItemID;
        partial void OnItemIDChanging(global::System.Nullable<int> value);
        partial void OnItemIDChanged();
        /// <summary>
        /// There are no comments for Property ParentItemID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> ParentItemID
        {
            get
            {
                return this._ParentItemID;
            }
            set
            {
                this.OnParentItemIDChanging(value);
                this.ReportPropertyChanging("ParentItemID");
                this._ParentItemID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ParentItemID");
                this.OnParentItemIDChanged();
            }
        }
        private global::System.Nullable<int> _ParentItemID;
        partial void OnParentItemIDChanging(global::System.Nullable<int> value);
        partial void OnParentItemIDChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this.ReportPropertyChanging("Title");
                this._Title = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Title");
                this.OnTitleChanged();
            }
        }
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property ItemFrame in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> ItemFrame
        {
            get
            {
                return this._ItemFrame;
            }
            set
            {
                this.OnItemFrameChanging(value);
                this.ReportPropertyChanging("ItemFrame");
                this._ItemFrame = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ItemFrame");
                this.OnItemFrameChanged();
            }
        }
        private global::System.Nullable<int> _ItemFrame;
        partial void OnItemFrameChanging(global::System.Nullable<int> value);
        partial void OnItemFrameChanged();
        /// <summary>
        /// There are no comments for Property ItemPosition in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<float> ItemPosition
        {
            get
            {
                return this._ItemPosition;
            }
            set
            {
                this.OnItemPositionChanging(value);
                this.ReportPropertyChanging("ItemPosition");
                this._ItemPosition = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ItemPosition");
                this.OnItemPositionChanged();
            }
        }
        private global::System.Nullable<float> _ItemPosition;
        partial void OnItemPositionChanging(global::System.Nullable<float> value);
        partial void OnItemPositionChanged();
        /// <summary>
        /// There are no comments for Property Notes in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes
        {
            get
            {
                return this._Notes;
            }
            set
            {
                this.OnNotesChanging(value);
                this.ReportPropertyChanging("Notes");
                this._Notes = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Notes");
                this.OnNotesChanged();
            }
        }
        private string _Notes;
        partial void OnNotesChanging(string value);
        partial void OnNotesChanged();
        /// <summary>
        /// There are no comments for Property DateSent in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> DateSent
        {
            get
            {
                return this._DateSent;
            }
            set
            {
                this.OnDateSentChanging(value);
                this.ReportPropertyChanging("DateSent");
                this._DateSent = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DateSent");
                this.OnDateSentChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _DateSent;
        partial void OnDateSentChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnDateSentChanged();
        /// <summary>
        /// There are no comments for Property DateReceived in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> DateReceived
        {
            get
            {
                return this._DateReceived;
            }
            set
            {
                this.OnDateReceivedChanging(value);
                this.ReportPropertyChanging("DateReceived");
                this._DateReceived = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DateReceived");
                this.OnDateReceivedChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _DateReceived;
        partial void OnDateReceivedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnDateReceivedChanged();
        /// <summary>
        /// There are no comments for Property DateCreated in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> DateCreated
        {
            get
            {
                return this._DateCreated;
            }
            set
            {
                this.OnDateCreatedChanging(value);
                this.ReportPropertyChanging("DateCreated");
                this._DateCreated = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DateCreated");
                this.OnDateCreatedChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _DateCreated;
        partial void OnDateCreatedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnDateCreatedChanged();
        /// <summary>
        /// There are no comments for Property DateModified in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> DateModified
        {
            get
            {
                return this._DateModified;
            }
            set
            {
                this.OnDateModifiedChanging(value);
                this.ReportPropertyChanging("DateModified");
                this._DateModified = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DateModified");
                this.OnDateModifiedChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _DateModified;
        partial void OnDateModifiedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnDateModifiedChanged();
        /// <summary>
        /// There are no comments for Property IsActive in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                this.OnIsActiveChanging(value);
                this.ReportPropertyChanging("IsActive");
                this._IsActive = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsActive");
                this.OnIsActiveChanged();
            }
        }
        private global::System.Nullable<bool> _IsActive;
        partial void OnIsActiveChanging(global::System.Nullable<bool> value);
        partial void OnIsActiveChanged();
    }
}
