//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenGOVideo.StorageService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StorageService.StorageServiceSoap")]
    public interface StorageServiceSoap {
        
        // CODEGEN: Generating message contract since message SaveAgendaFileRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveAgendaFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        OpenGOVideo.StorageService.SaveAgendaFileResponse SaveAgendaFile(OpenGOVideo.StorageService.SaveAgendaFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAgendaFileFromWebServer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string GetAgendaFileFromWebServer(string City, string State, string Board, string FileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAvailableAgendaFiles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        OpenGOVideo.StorageService.AgendaFile[] GetAvailableAgendaFiles(string City, string State, string Board);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAvailableAgendaFilesAndDates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        OpenGOVideo.StorageService.AgendaFile[] GetAvailableAgendaFilesAndDates(string City, string State, string Board);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenTokenHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private string pathField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
                this.RaisePropertyChanged("Path");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AgendaFile : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fileNameField;
        
        private string dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("FileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveAgendaFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveAgendaFileRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public OpenGOVideo.StorageService.AuthenTokenHeader AuthenTokenHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Payload;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string FileName;
        
        public SaveAgendaFileRequest() {
        }
        
        public SaveAgendaFileRequest(OpenGOVideo.StorageService.AuthenTokenHeader AuthenTokenHeader, string Payload, string FileName) {
            this.AuthenTokenHeader = AuthenTokenHeader;
            this.Payload = Payload;
            this.FileName = FileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveAgendaFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveAgendaFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SaveAgendaFileResult;
        
        public SaveAgendaFileResponse() {
        }
        
        public SaveAgendaFileResponse(bool SaveAgendaFileResult) {
            this.SaveAgendaFileResult = SaveAgendaFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StorageServiceSoapChannel : OpenGOVideo.StorageService.StorageServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StorageServiceSoapClient : System.ServiceModel.ClientBase<OpenGOVideo.StorageService.StorageServiceSoap>, OpenGOVideo.StorageService.StorageServiceSoap {
        
        public StorageServiceSoapClient() {
        }
        
        public StorageServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StorageServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StorageServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StorageServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OpenGOVideo.StorageService.SaveAgendaFileResponse OpenGOVideo.StorageService.StorageServiceSoap.SaveAgendaFile(OpenGOVideo.StorageService.SaveAgendaFileRequest request) {
            return base.Channel.SaveAgendaFile(request);
        }
        
        public bool SaveAgendaFile(OpenGOVideo.StorageService.AuthenTokenHeader AuthenTokenHeader, string Payload, string FileName) {
            OpenGOVideo.StorageService.SaveAgendaFileRequest inValue = new OpenGOVideo.StorageService.SaveAgendaFileRequest();
            inValue.AuthenTokenHeader = AuthenTokenHeader;
            inValue.Payload = Payload;
            inValue.FileName = FileName;
            OpenGOVideo.StorageService.SaveAgendaFileResponse retVal = ((OpenGOVideo.StorageService.StorageServiceSoap)(this)).SaveAgendaFile(inValue);
            return retVal.SaveAgendaFileResult;
        }
        
        public string GetAgendaFileFromWebServer(string City, string State, string Board, string FileName) {
            return base.Channel.GetAgendaFileFromWebServer(City, State, Board, FileName);
        }
        
        public OpenGOVideo.StorageService.AgendaFile[] GetAvailableAgendaFiles(string City, string State, string Board) {
            return base.Channel.GetAvailableAgendaFiles(City, State, Board);
        }
        
        public OpenGOVideo.StorageService.AgendaFile[] GetAvailableAgendaFilesAndDates(string City, string State, string Board) {
            return base.Channel.GetAvailableAgendaFilesAndDates(City, State, Board);
        }
    }
}
